site_name: Example MkDocs Documents
docs_dir: .
site_description: 'Example MkDocs Documents'
site_author: 'Steve Zuar'

theme:
  name: material
  features:
    - content.code.annotate
    - toc.integrate
    # - navigation.sections
    # - navigation.tabs
    
plugins:
   - search
   - include-markdown
   - awesome-pages
   - same-dir

markdown_extensions:
   - admonition
   - codehilite
   - def_list
   - fenced_code
   - footnotes
   - mkdocs_graphviz
   - markdown_include_lines.main:
        base_path: docs/
   - markdown_include.include:
        base_path: docs/
   - meta        
   - pymdownx.details
   - pymdownx.highlight:
       use_pygments: true
   - pymdownx.inlinehilite
   - pymdownx.snippets:
       base_path: docs/
   - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed:
       alternate_style: true
   - tables
   - toc:
       title: On this page
       permalink: true
       permalink_title: Permanent link to this section for reference

extra_css:
  - css/pygments.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js  
